// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	asynqpg "github.com/yakser/asynqpg"

	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/yakser/asynqpg/internal/repository"
)

// TaskRepository is an autogenerated mock type for the taskRepository type
type TaskRepository struct {
	mock.Mock
}

type TaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskRepository) EXPECT() *TaskRepository_Expecter {
	return &TaskRepository_Expecter{mock: &_m.Mock}
}

// CancelTaskByID provides a mock function with given fields: ctx, id
func (_m *TaskRepository) CancelTaskByID(ctx context.Context, id int64) (*repository.FullTask, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelTaskByID")
	}

	var r0 *repository.FullTask
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.FullTask, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.FullTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskRepository_CancelTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTaskByID'
type TaskRepository_CancelTaskByID_Call struct {
	*mock.Call
}

// CancelTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TaskRepository_Expecter) CancelTaskByID(ctx interface{}, id interface{}) *TaskRepository_CancelTaskByID_Call {
	return &TaskRepository_CancelTaskByID_Call{Call: _e.mock.On("CancelTaskByID", ctx, id)}
}

func (_c *TaskRepository_CancelTaskByID_Call) Run(run func(ctx context.Context, id int64)) *TaskRepository_CancelTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TaskRepository_CancelTaskByID_Call) Return(_a0 *repository.FullTask, _a1 bool, _a2 error) *TaskRepository_CancelTaskByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskRepository_CancelTaskByID_Call) RunAndReturn(run func(context.Context, int64) (*repository.FullTask, bool, error)) *TaskRepository_CancelTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// CancelTaskByIDWithTx provides a mock function with given fields: ctx, tx, id
func (_m *TaskRepository) CancelTaskByIDWithTx(ctx context.Context, tx asynqpg.Tx, id int64) (*repository.FullTask, bool, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelTaskByIDWithTx")
	}

	var r0 *repository.FullTask
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, bool, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) *repository.FullTask); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, asynqpg.Tx, int64) bool); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, asynqpg.Tx, int64) error); ok {
		r2 = rf(ctx, tx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskRepository_CancelTaskByIDWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTaskByIDWithTx'
type TaskRepository_CancelTaskByIDWithTx_Call struct {
	*mock.Call
}

// CancelTaskByIDWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx asynqpg.Tx
//   - id int64
func (_e *TaskRepository_Expecter) CancelTaskByIDWithTx(ctx interface{}, tx interface{}, id interface{}) *TaskRepository_CancelTaskByIDWithTx_Call {
	return &TaskRepository_CancelTaskByIDWithTx_Call{Call: _e.mock.On("CancelTaskByIDWithTx", ctx, tx, id)}
}

func (_c *TaskRepository_CancelTaskByIDWithTx_Call) Run(run func(ctx context.Context, tx asynqpg.Tx, id int64)) *TaskRepository_CancelTaskByIDWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(asynqpg.Tx), args[2].(int64))
	})
	return _c
}

func (_c *TaskRepository_CancelTaskByIDWithTx_Call) Return(_a0 *repository.FullTask, _a1 bool, _a2 error) *TaskRepository_CancelTaskByIDWithTx_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskRepository_CancelTaskByIDWithTx_Call) RunAndReturn(run func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, bool, error)) *TaskRepository_CancelTaskByIDWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskByID provides a mock function with given fields: ctx, id
func (_m *TaskRepository) DeleteTaskByID(ctx context.Context, id int64) (*repository.FullTask, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskByID")
	}

	var r0 *repository.FullTask
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.FullTask, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.FullTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskRepository_DeleteTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskByID'
type TaskRepository_DeleteTaskByID_Call struct {
	*mock.Call
}

// DeleteTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TaskRepository_Expecter) DeleteTaskByID(ctx interface{}, id interface{}) *TaskRepository_DeleteTaskByID_Call {
	return &TaskRepository_DeleteTaskByID_Call{Call: _e.mock.On("DeleteTaskByID", ctx, id)}
}

func (_c *TaskRepository_DeleteTaskByID_Call) Run(run func(ctx context.Context, id int64)) *TaskRepository_DeleteTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TaskRepository_DeleteTaskByID_Call) Return(_a0 *repository.FullTask, _a1 bool, _a2 error) *TaskRepository_DeleteTaskByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskRepository_DeleteTaskByID_Call) RunAndReturn(run func(context.Context, int64) (*repository.FullTask, bool, error)) *TaskRepository_DeleteTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTaskByIDWithTx provides a mock function with given fields: ctx, tx, id
func (_m *TaskRepository) DeleteTaskByIDWithTx(ctx context.Context, tx asynqpg.Tx, id int64) (*repository.FullTask, bool, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskByIDWithTx")
	}

	var r0 *repository.FullTask
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, bool, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) *repository.FullTask); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, asynqpg.Tx, int64) bool); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, asynqpg.Tx, int64) error); ok {
		r2 = rf(ctx, tx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskRepository_DeleteTaskByIDWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTaskByIDWithTx'
type TaskRepository_DeleteTaskByIDWithTx_Call struct {
	*mock.Call
}

// DeleteTaskByIDWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx asynqpg.Tx
//   - id int64
func (_e *TaskRepository_Expecter) DeleteTaskByIDWithTx(ctx interface{}, tx interface{}, id interface{}) *TaskRepository_DeleteTaskByIDWithTx_Call {
	return &TaskRepository_DeleteTaskByIDWithTx_Call{Call: _e.mock.On("DeleteTaskByIDWithTx", ctx, tx, id)}
}

func (_c *TaskRepository_DeleteTaskByIDWithTx_Call) Run(run func(ctx context.Context, tx asynqpg.Tx, id int64)) *TaskRepository_DeleteTaskByIDWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(asynqpg.Tx), args[2].(int64))
	})
	return _c
}

func (_c *TaskRepository_DeleteTaskByIDWithTx_Call) Return(_a0 *repository.FullTask, _a1 bool, _a2 error) *TaskRepository_DeleteTaskByIDWithTx_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskRepository_DeleteTaskByIDWithTx_Call) RunAndReturn(run func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, bool, error)) *TaskRepository_DeleteTaskByIDWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function with given fields: ctx, id
func (_m *TaskRepository) GetTaskByID(ctx context.Context, id int64) (*repository.FullTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *repository.FullTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.FullTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.FullTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type TaskRepository_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TaskRepository_Expecter) GetTaskByID(ctx interface{}, id interface{}) *TaskRepository_GetTaskByID_Call {
	return &TaskRepository_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", ctx, id)}
}

func (_c *TaskRepository_GetTaskByID_Call) Run(run func(ctx context.Context, id int64)) *TaskRepository_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TaskRepository_GetTaskByID_Call) Return(_a0 *repository.FullTask, _a1 error) *TaskRepository_GetTaskByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_GetTaskByID_Call) RunAndReturn(run func(context.Context, int64) (*repository.FullTask, error)) *TaskRepository_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByIDWithTx provides a mock function with given fields: ctx, tx, id
func (_m *TaskRepository) GetTaskByIDWithTx(ctx context.Context, tx asynqpg.Tx, id int64) (*repository.FullTask, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByIDWithTx")
	}

	var r0 *repository.FullTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) *repository.FullTask); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, asynqpg.Tx, int64) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_GetTaskByIDWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByIDWithTx'
type TaskRepository_GetTaskByIDWithTx_Call struct {
	*mock.Call
}

// GetTaskByIDWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx asynqpg.Tx
//   - id int64
func (_e *TaskRepository_Expecter) GetTaskByIDWithTx(ctx interface{}, tx interface{}, id interface{}) *TaskRepository_GetTaskByIDWithTx_Call {
	return &TaskRepository_GetTaskByIDWithTx_Call{Call: _e.mock.On("GetTaskByIDWithTx", ctx, tx, id)}
}

func (_c *TaskRepository_GetTaskByIDWithTx_Call) Run(run func(ctx context.Context, tx asynqpg.Tx, id int64)) *TaskRepository_GetTaskByIDWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(asynqpg.Tx), args[2].(int64))
	})
	return _c
}

func (_c *TaskRepository_GetTaskByIDWithTx_Call) Return(_a0 *repository.FullTask, _a1 error) *TaskRepository_GetTaskByIDWithTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_GetTaskByIDWithTx_Call) RunAndReturn(run func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, error)) *TaskRepository_GetTaskByIDWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx, params
func (_m *TaskRepository) ListTasks(ctx context.Context, params repository.ListTasksParams) (*repository.ListTasksResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 *repository.ListTasksResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksParams) (*repository.ListTasksResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksParams) *repository.ListTasksResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListTasksResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListTasksParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type TaskRepository_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.ListTasksParams
func (_e *TaskRepository_Expecter) ListTasks(ctx interface{}, params interface{}) *TaskRepository_ListTasks_Call {
	return &TaskRepository_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, params)}
}

func (_c *TaskRepository_ListTasks_Call) Run(run func(ctx context.Context, params repository.ListTasksParams)) *TaskRepository_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ListTasksParams))
	})
	return _c
}

func (_c *TaskRepository_ListTasks_Call) Return(_a0 *repository.ListTasksResult, _a1 error) *TaskRepository_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_ListTasks_Call) RunAndReturn(run func(context.Context, repository.ListTasksParams) (*repository.ListTasksResult, error)) *TaskRepository_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasksWithTx provides a mock function with given fields: ctx, tx, params
func (_m *TaskRepository) ListTasksWithTx(ctx context.Context, tx asynqpg.Tx, params repository.ListTasksParams) (*repository.ListTasksResult, error) {
	ret := _m.Called(ctx, tx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListTasksWithTx")
	}

	var r0 *repository.ListTasksResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, repository.ListTasksParams) (*repository.ListTasksResult, error)); ok {
		return rf(ctx, tx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, repository.ListTasksParams) *repository.ListTasksResult); ok {
		r0 = rf(ctx, tx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListTasksResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, asynqpg.Tx, repository.ListTasksParams) error); ok {
		r1 = rf(ctx, tx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskRepository_ListTasksWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasksWithTx'
type TaskRepository_ListTasksWithTx_Call struct {
	*mock.Call
}

// ListTasksWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx asynqpg.Tx
//   - params repository.ListTasksParams
func (_e *TaskRepository_Expecter) ListTasksWithTx(ctx interface{}, tx interface{}, params interface{}) *TaskRepository_ListTasksWithTx_Call {
	return &TaskRepository_ListTasksWithTx_Call{Call: _e.mock.On("ListTasksWithTx", ctx, tx, params)}
}

func (_c *TaskRepository_ListTasksWithTx_Call) Run(run func(ctx context.Context, tx asynqpg.Tx, params repository.ListTasksParams)) *TaskRepository_ListTasksWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(asynqpg.Tx), args[2].(repository.ListTasksParams))
	})
	return _c
}

func (_c *TaskRepository_ListTasksWithTx_Call) Return(_a0 *repository.ListTasksResult, _a1 error) *TaskRepository_ListTasksWithTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskRepository_ListTasksWithTx_Call) RunAndReturn(run func(context.Context, asynqpg.Tx, repository.ListTasksParams) (*repository.ListTasksResult, error)) *TaskRepository_ListTasksWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// RetryTaskByID provides a mock function with given fields: ctx, id
func (_m *TaskRepository) RetryTaskByID(ctx context.Context, id int64) (*repository.FullTask, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetryTaskByID")
	}

	var r0 *repository.FullTask
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.FullTask, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.FullTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskRepository_RetryTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryTaskByID'
type TaskRepository_RetryTaskByID_Call struct {
	*mock.Call
}

// RetryTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TaskRepository_Expecter) RetryTaskByID(ctx interface{}, id interface{}) *TaskRepository_RetryTaskByID_Call {
	return &TaskRepository_RetryTaskByID_Call{Call: _e.mock.On("RetryTaskByID", ctx, id)}
}

func (_c *TaskRepository_RetryTaskByID_Call) Run(run func(ctx context.Context, id int64)) *TaskRepository_RetryTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TaskRepository_RetryTaskByID_Call) Return(_a0 *repository.FullTask, _a1 bool, _a2 error) *TaskRepository_RetryTaskByID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskRepository_RetryTaskByID_Call) RunAndReturn(run func(context.Context, int64) (*repository.FullTask, bool, error)) *TaskRepository_RetryTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// RetryTaskByIDWithTx provides a mock function with given fields: ctx, tx, id
func (_m *TaskRepository) RetryTaskByIDWithTx(ctx context.Context, tx asynqpg.Tx, id int64) (*repository.FullTask, bool, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetryTaskByIDWithTx")
	}

	var r0 *repository.FullTask
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, bool, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, int64) *repository.FullTask); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.FullTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, asynqpg.Tx, int64) bool); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, asynqpg.Tx, int64) error); ok {
		r2 = rf(ctx, tx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TaskRepository_RetryTaskByIDWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryTaskByIDWithTx'
type TaskRepository_RetryTaskByIDWithTx_Call struct {
	*mock.Call
}

// RetryTaskByIDWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx asynqpg.Tx
//   - id int64
func (_e *TaskRepository_Expecter) RetryTaskByIDWithTx(ctx interface{}, tx interface{}, id interface{}) *TaskRepository_RetryTaskByIDWithTx_Call {
	return &TaskRepository_RetryTaskByIDWithTx_Call{Call: _e.mock.On("RetryTaskByIDWithTx", ctx, tx, id)}
}

func (_c *TaskRepository_RetryTaskByIDWithTx_Call) Run(run func(ctx context.Context, tx asynqpg.Tx, id int64)) *TaskRepository_RetryTaskByIDWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(asynqpg.Tx), args[2].(int64))
	})
	return _c
}

func (_c *TaskRepository_RetryTaskByIDWithTx_Call) Return(_a0 *repository.FullTask, _a1 bool, _a2 error) *TaskRepository_RetryTaskByIDWithTx_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TaskRepository_RetryTaskByIDWithTx_Call) RunAndReturn(run func(context.Context, asynqpg.Tx, int64) (*repository.FullTask, bool, error)) *TaskRepository_RetryTaskByIDWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
