// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	uiauth "github.com/yakser/asynqpg/ui/uiauth"
)

// AuthProvider is an autogenerated mock type for the AuthProvider type
type AuthProvider struct {
	mock.Mock
}

type AuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthProvider) EXPECT() *AuthProvider_Expecter {
	return &AuthProvider_Expecter{mock: &_m.Mock}
}

// BeginAuth provides a mock function with given fields: w, r, callbackURL, state
func (_m *AuthProvider) BeginAuth(w http.ResponseWriter, r *http.Request, callbackURL string, state string) {
	_m.Called(w, r, callbackURL, state)
}

// AuthProvider_BeginAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginAuth'
type AuthProvider_BeginAuth_Call struct {
	*mock.Call
}

// BeginAuth is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - callbackURL string
//   - state string
func (_e *AuthProvider_Expecter) BeginAuth(w interface{}, r interface{}, callbackURL interface{}, state interface{}) *AuthProvider_BeginAuth_Call {
	return &AuthProvider_BeginAuth_Call{Call: _e.mock.On("BeginAuth", w, r, callbackURL, state)}
}

func (_c *AuthProvider_BeginAuth_Call) Run(run func(w http.ResponseWriter, r *http.Request, callbackURL string, state string)) *AuthProvider_BeginAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AuthProvider_BeginAuth_Call) Return() *AuthProvider_BeginAuth_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthProvider_BeginAuth_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request, string, string)) *AuthProvider_BeginAuth_Call {
	_c.Run(run)
	return _c
}

// CompleteAuth provides a mock function with given fields: w, r
func (_m *AuthProvider) CompleteAuth(w http.ResponseWriter, r *http.Request) (*uiauth.User, error) {
	ret := _m.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for CompleteAuth")
	}

	var r0 *uiauth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) (*uiauth.User, error)); ok {
		return rf(w, r)
	}
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) *uiauth.User); ok {
		r0 = rf(w, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uiauth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(http.ResponseWriter, *http.Request) error); ok {
		r1 = rf(w, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthProvider_CompleteAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteAuth'
type AuthProvider_CompleteAuth_Call struct {
	*mock.Call
}

// CompleteAuth is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthProvider_Expecter) CompleteAuth(w interface{}, r interface{}) *AuthProvider_CompleteAuth_Call {
	return &AuthProvider_CompleteAuth_Call{Call: _e.mock.On("CompleteAuth", w, r)}
}

func (_c *AuthProvider_CompleteAuth_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthProvider_CompleteAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthProvider_CompleteAuth_Call) Return(_a0 *uiauth.User, _a1 error) *AuthProvider_CompleteAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthProvider_CompleteAuth_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request) (*uiauth.User, error)) *AuthProvider_CompleteAuth_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function with no fields
func (_m *AuthProvider) DisplayName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AuthProvider_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type AuthProvider_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *AuthProvider_Expecter) DisplayName() *AuthProvider_DisplayName_Call {
	return &AuthProvider_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *AuthProvider_DisplayName_Call) Run(run func()) *AuthProvider_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthProvider_DisplayName_Call) Return(_a0 string) *AuthProvider_DisplayName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthProvider_DisplayName_Call) RunAndReturn(run func() string) *AuthProvider_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *AuthProvider) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AuthProvider_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type AuthProvider_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *AuthProvider_Expecter) ID() *AuthProvider_ID_Call {
	return &AuthProvider_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *AuthProvider_ID_Call) Run(run func()) *AuthProvider_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthProvider_ID_Call) Return(_a0 string) *AuthProvider_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthProvider_ID_Call) RunAndReturn(run func() string) *AuthProvider_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IconURL provides a mock function with no fields
func (_m *AuthProvider) IconURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IconURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AuthProvider_IconURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IconURL'
type AuthProvider_IconURL_Call struct {
	*mock.Call
}

// IconURL is a helper method to define mock.On call
func (_e *AuthProvider_Expecter) IconURL() *AuthProvider_IconURL_Call {
	return &AuthProvider_IconURL_Call{Call: _e.mock.On("IconURL")}
}

func (_c *AuthProvider_IconURL_Call) Run(run func()) *AuthProvider_IconURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthProvider_IconURL_Call) Return(_a0 string) *AuthProvider_IconURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthProvider_IconURL_Call) RunAndReturn(run func() string) *AuthProvider_IconURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthProvider creates a new instance of AuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthProvider {
	mock := &AuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
