// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uiauth "github.com/yakser/asynqpg/ui/uiauth"
)

// SessionStore is an autogenerated mock type for the SessionStore type
type SessionStore struct {
	mock.Mock
}

type SessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionStore) EXPECT() *SessionStore_Expecter {
	return &SessionStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, token
func (_m *SessionStore) Delete(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SessionStore_Expecter) Delete(ctx interface{}, token interface{}) *SessionStore_Delete_Call {
	return &SessionStore_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *SessionStore_Delete_Call) Run(run func(ctx context.Context, token string)) *SessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_Delete_Call) Return(_a0 error) *SessionStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *SessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, token
func (_m *SessionStore) Get(ctx context.Context, token string) (*uiauth.Session, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *uiauth.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*uiauth.Session, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *uiauth.Session); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uiauth.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SessionStore_Expecter) Get(ctx interface{}, token interface{}) *SessionStore_Get_Call {
	return &SessionStore_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *SessionStore_Get_Call) Run(run func(ctx context.Context, token string)) *SessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionStore_Get_Call) Return(_a0 *uiauth.Session, _a1 error) *SessionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionStore_Get_Call) RunAndReturn(run func(context.Context, string) (*uiauth.Session, error)) *SessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, session
func (_m *SessionStore) Save(ctx context.Context, session *uiauth.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *uiauth.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type SessionStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - session *uiauth.Session
func (_e *SessionStore_Expecter) Save(ctx interface{}, session interface{}) *SessionStore_Save_Call {
	return &SessionStore_Save_Call{Call: _e.mock.On("Save", ctx, session)}
}

func (_c *SessionStore_Save_Call) Run(run func(ctx context.Context, session *uiauth.Session)) *SessionStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uiauth.Session))
	})
	return _c
}

func (_c *SessionStore_Save_Call) Return(_a0 error) *SessionStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionStore_Save_Call) RunAndReturn(run func(context.Context, *uiauth.Session) error) *SessionStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionStore creates a new instance of SessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStore {
	mock := &SessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
