// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repository "github.com/yakser/asynqpg/internal/repository"
)

// CompleterRepo is an autogenerated mock type for the completerRepo type
type CompleterRepo struct {
	mock.Mock
}

type CompleterRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CompleterRepo) EXPECT() *CompleterRepo_Expecter {
	return &CompleterRepo_Expecter{mock: &_m.Mock}
}

// CompleteTasksMany provides a mock function with given fields: ctx, params
func (_m *CompleterRepo) CompleteTasksMany(ctx context.Context, params repository.CompleteTasksManyParams) (int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTasksMany")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CompleteTasksManyParams) (int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CompleteTasksManyParams) int); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CompleteTasksManyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleterRepo_CompleteTasksMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteTasksMany'
type CompleterRepo_CompleteTasksMany_Call struct {
	*mock.Call
}

// CompleteTasksMany is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.CompleteTasksManyParams
func (_e *CompleterRepo_Expecter) CompleteTasksMany(ctx interface{}, params interface{}) *CompleterRepo_CompleteTasksMany_Call {
	return &CompleterRepo_CompleteTasksMany_Call{Call: _e.mock.On("CompleteTasksMany", ctx, params)}
}

func (_c *CompleterRepo_CompleteTasksMany_Call) Run(run func(ctx context.Context, params repository.CompleteTasksManyParams)) *CompleterRepo_CompleteTasksMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CompleteTasksManyParams))
	})
	return _c
}

func (_c *CompleterRepo_CompleteTasksMany_Call) Return(_a0 int, _a1 error) *CompleterRepo_CompleteTasksMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompleterRepo_CompleteTasksMany_Call) RunAndReturn(run func(context.Context, repository.CompleteTasksManyParams) (int, error)) *CompleterRepo_CompleteTasksMany_Call {
	_c.Call.Return(run)
	return _c
}

// FailTasksMany provides a mock function with given fields: ctx, params
func (_m *CompleterRepo) FailTasksMany(ctx context.Context, params repository.FailTasksManyParams) (int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for FailTasksMany")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.FailTasksManyParams) (int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.FailTasksManyParams) int); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.FailTasksManyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleterRepo_FailTasksMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailTasksMany'
type CompleterRepo_FailTasksMany_Call struct {
	*mock.Call
}

// FailTasksMany is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.FailTasksManyParams
func (_e *CompleterRepo_Expecter) FailTasksMany(ctx interface{}, params interface{}) *CompleterRepo_FailTasksMany_Call {
	return &CompleterRepo_FailTasksMany_Call{Call: _e.mock.On("FailTasksMany", ctx, params)}
}

func (_c *CompleterRepo_FailTasksMany_Call) Run(run func(ctx context.Context, params repository.FailTasksManyParams)) *CompleterRepo_FailTasksMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.FailTasksManyParams))
	})
	return _c
}

func (_c *CompleterRepo_FailTasksMany_Call) Return(_a0 int, _a1 error) *CompleterRepo_FailTasksMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompleterRepo_FailTasksMany_Call) RunAndReturn(run func(context.Context, repository.FailTasksManyParams) (int, error)) *CompleterRepo_FailTasksMany_Call {
	_c.Call.Return(run)
	return _c
}

// RetryTasksMany provides a mock function with given fields: ctx, params
func (_m *CompleterRepo) RetryTasksMany(ctx context.Context, params repository.RetryTasksManyParams) (int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RetryTasksMany")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.RetryTasksManyParams) (int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.RetryTasksManyParams) int); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.RetryTasksManyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleterRepo_RetryTasksMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryTasksMany'
type CompleterRepo_RetryTasksMany_Call struct {
	*mock.Call
}

// RetryTasksMany is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.RetryTasksManyParams
func (_e *CompleterRepo_Expecter) RetryTasksMany(ctx interface{}, params interface{}) *CompleterRepo_RetryTasksMany_Call {
	return &CompleterRepo_RetryTasksMany_Call{Call: _e.mock.On("RetryTasksMany", ctx, params)}
}

func (_c *CompleterRepo_RetryTasksMany_Call) Run(run func(ctx context.Context, params repository.RetryTasksManyParams)) *CompleterRepo_RetryTasksMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.RetryTasksManyParams))
	})
	return _c
}

func (_c *CompleterRepo_RetryTasksMany_Call) Return(_a0 int, _a1 error) *CompleterRepo_RetryTasksMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompleterRepo_RetryTasksMany_Call) RunAndReturn(run func(context.Context, repository.RetryTasksManyParams) (int, error)) *CompleterRepo_RetryTasksMany_Call {
	_c.Call.Return(run)
	return _c
}

// SnoozeTasksMany provides a mock function with given fields: ctx, params
func (_m *CompleterRepo) SnoozeTasksMany(ctx context.Context, params repository.SnoozeTasksManyParams) (int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SnoozeTasksMany")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SnoozeTasksManyParams) (int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.SnoozeTasksManyParams) int); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.SnoozeTasksManyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleterRepo_SnoozeTasksMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnoozeTasksMany'
type CompleterRepo_SnoozeTasksMany_Call struct {
	*mock.Call
}

// SnoozeTasksMany is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.SnoozeTasksManyParams
func (_e *CompleterRepo_Expecter) SnoozeTasksMany(ctx interface{}, params interface{}) *CompleterRepo_SnoozeTasksMany_Call {
	return &CompleterRepo_SnoozeTasksMany_Call{Call: _e.mock.On("SnoozeTasksMany", ctx, params)}
}

func (_c *CompleterRepo_SnoozeTasksMany_Call) Run(run func(ctx context.Context, params repository.SnoozeTasksManyParams)) *CompleterRepo_SnoozeTasksMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.SnoozeTasksManyParams))
	})
	return _c
}

func (_c *CompleterRepo_SnoozeTasksMany_Call) Return(_a0 int, _a1 error) *CompleterRepo_SnoozeTasksMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompleterRepo_SnoozeTasksMany_Call) RunAndReturn(run func(context.Context, repository.SnoozeTasksManyParams) (int, error)) *CompleterRepo_SnoozeTasksMany_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompleterRepo creates a new instance of CompleterRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompleterRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompleterRepo {
	mock := &CompleterRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
