// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	asynqpg "github.com/yakser/asynqpg"

	mock "github.com/stretchr/testify/mock"
)

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

type ErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorHandler) EXPECT() *ErrorHandler_Expecter {
	return &ErrorHandler_Expecter{mock: &_m.Mock}
}

// HandleError provides a mock function with given fields: ctx, task, err
func (_m *ErrorHandler) HandleError(ctx context.Context, task *asynqpg.TaskInfo, err error) {
	_m.Called(ctx, task, err)
}

// ErrorHandler_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type ErrorHandler_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - ctx context.Context
//   - task *asynqpg.TaskInfo
//   - err error
func (_e *ErrorHandler_Expecter) HandleError(ctx interface{}, task interface{}, err interface{}) *ErrorHandler_HandleError_Call {
	return &ErrorHandler_HandleError_Call{Call: _e.mock.On("HandleError", ctx, task, err)}
}

func (_c *ErrorHandler_HandleError_Call) Run(run func(ctx context.Context, task *asynqpg.TaskInfo, err error)) *ErrorHandler_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*asynqpg.TaskInfo), args[2].(error))
	})
	return _c
}

func (_c *ErrorHandler_HandleError_Call) Return() *ErrorHandler_HandleError_Call {
	_c.Call.Return()
	return _c
}

func (_c *ErrorHandler_HandleError_Call) RunAndReturn(run func(context.Context, *asynqpg.TaskInfo, error)) *ErrorHandler_HandleError_Call {
	_c.Run(run)
	return _c
}

// NewErrorHandler creates a new instance of ErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorHandler {
	mock := &ErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
