// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// RetryPolicy is an autogenerated mock type for the RetryPolicy type
type RetryPolicy struct {
	mock.Mock
}

type RetryPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *RetryPolicy) EXPECT() *RetryPolicy_Expecter {
	return &RetryPolicy_Expecter{mock: &_m.Mock}
}

// NextRetry provides a mock function with given fields: attempt
func (_m *RetryPolicy) NextRetry(attempt int) time.Duration {
	ret := _m.Called(attempt)

	if len(ret) == 0 {
		panic("no return value specified for NextRetry")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(int) time.Duration); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// RetryPolicy_NextRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextRetry'
type RetryPolicy_NextRetry_Call struct {
	*mock.Call
}

// NextRetry is a helper method to define mock.On call
//   - attempt int
func (_e *RetryPolicy_Expecter) NextRetry(attempt interface{}) *RetryPolicy_NextRetry_Call {
	return &RetryPolicy_NextRetry_Call{Call: _e.mock.On("NextRetry", attempt)}
}

func (_c *RetryPolicy_NextRetry_Call) Run(run func(attempt int)) *RetryPolicy_NextRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *RetryPolicy_NextRetry_Call) Return(_a0 time.Duration) *RetryPolicy_NextRetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryPolicy_NextRetry_Call) RunAndReturn(run func(int) time.Duration) *RetryPolicy_NextRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetryPolicy creates a new instance of RetryPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryPolicy {
	mock := &RetryPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
