// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Completer is an autogenerated mock type for the Completer type
type Completer struct {
	mock.Mock
}

type Completer_Expecter struct {
	mock *mock.Mock
}

func (_m *Completer) EXPECT() *Completer_Expecter {
	return &Completer_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: taskID
func (_m *Completer) Complete(taskID int64) error {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Completer_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type Completer_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - taskID int64
func (_e *Completer_Expecter) Complete(taskID interface{}) *Completer_Complete_Call {
	return &Completer_Complete_Call{Call: _e.mock.On("Complete", taskID)}
}

func (_c *Completer_Complete_Call) Run(run func(taskID int64)) *Completer_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *Completer_Complete_Call) Return(_a0 error) *Completer_Complete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Completer_Complete_Call) RunAndReturn(run func(int64) error) *Completer_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function with given fields: taskID, message
func (_m *Completer) Fail(taskID int64, message string) error {
	ret := _m.Called(taskID, message)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = rf(taskID, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Completer_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type Completer_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - taskID int64
//   - message string
func (_e *Completer_Expecter) Fail(taskID interface{}, message interface{}) *Completer_Fail_Call {
	return &Completer_Fail_Call{Call: _e.mock.On("Fail", taskID, message)}
}

func (_c *Completer_Fail_Call) Run(run func(taskID int64, message string)) *Completer_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *Completer_Fail_Call) Return(_a0 error) *Completer_Fail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Completer_Fail_Call) RunAndReturn(run func(int64, string) error) *Completer_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// Retry provides a mock function with given fields: taskID, blockedTill, message
func (_m *Completer) Retry(taskID int64, blockedTill time.Time, message string) error {
	ret := _m.Called(taskID, blockedTill, message)

	if len(ret) == 0 {
		panic("no return value specified for Retry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, time.Time, string) error); ok {
		r0 = rf(taskID, blockedTill, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Completer_Retry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retry'
type Completer_Retry_Call struct {
	*mock.Call
}

// Retry is a helper method to define mock.On call
//   - taskID int64
//   - blockedTill time.Time
//   - message string
func (_e *Completer_Expecter) Retry(taskID interface{}, blockedTill interface{}, message interface{}) *Completer_Retry_Call {
	return &Completer_Retry_Call{Call: _e.mock.On("Retry", taskID, blockedTill, message)}
}

func (_c *Completer_Retry_Call) Run(run func(taskID int64, blockedTill time.Time, message string)) *Completer_Retry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(time.Time), args[2].(string))
	})
	return _c
}

func (_c *Completer_Retry_Call) Return(_a0 error) *Completer_Retry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Completer_Retry_Call) RunAndReturn(run func(int64, time.Time, string) error) *Completer_Retry_Call {
	_c.Call.Return(run)
	return _c
}

// Snooze provides a mock function with given fields: taskID, blockedTill
func (_m *Completer) Snooze(taskID int64, blockedTill time.Time) error {
	ret := _m.Called(taskID, blockedTill)

	if len(ret) == 0 {
		panic("no return value specified for Snooze")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, time.Time) error); ok {
		r0 = rf(taskID, blockedTill)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Completer_Snooze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snooze'
type Completer_Snooze_Call struct {
	*mock.Call
}

// Snooze is a helper method to define mock.On call
//   - taskID int64
//   - blockedTill time.Time
func (_e *Completer_Expecter) Snooze(taskID interface{}, blockedTill interface{}) *Completer_Snooze_Call {
	return &Completer_Snooze_Call{Call: _e.mock.On("Snooze", taskID, blockedTill)}
}

func (_c *Completer_Snooze_Call) Run(run func(taskID int64, blockedTill time.Time)) *Completer_Snooze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(time.Time))
	})
	return _c
}

func (_c *Completer_Snooze_Call) Return(_a0 error) *Completer_Snooze_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Completer_Snooze_Call) RunAndReturn(run func(int64, time.Time) error) *Completer_Snooze_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *Completer) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Completer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Completer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Completer_Expecter) Start(ctx interface{}) *Completer_Start_Call {
	return &Completer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Completer_Start_Call) Run(run func(ctx context.Context)) *Completer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Completer_Start_Call) Return(_a0 error) *Completer_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Completer_Start_Call) RunAndReturn(run func(context.Context) error) *Completer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Completer) Stop() {
	_m.Called()
}

// Completer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Completer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Completer_Expecter) Stop() *Completer_Stop_Call {
	return &Completer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Completer_Stop_Call) Run(run func()) *Completer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Completer_Stop_Call) Return() *Completer_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Completer_Stop_Call) RunAndReturn(run func()) *Completer_Stop_Call {
	_c.Run(run)
	return _c
}

// NewCompleter creates a new instance of Completer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Completer {
	mock := &Completer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
