// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	asynqpg "github.com/yakser/asynqpg"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TaskHandler is an autogenerated mock type for the TaskHandler type
type TaskHandler struct {
	mock.Mock
}

type TaskHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskHandler) EXPECT() *TaskHandler_Expecter {
	return &TaskHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, task
func (_m *TaskHandler) Handle(ctx context.Context, task *asynqpg.TaskInfo) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *asynqpg.TaskInfo) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type TaskHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - task *asynqpg.TaskInfo
func (_e *TaskHandler_Expecter) Handle(ctx interface{}, task interface{}) *TaskHandler_Handle_Call {
	return &TaskHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, task)}
}

func (_c *TaskHandler_Handle_Call) Run(run func(ctx context.Context, task *asynqpg.TaskInfo)) *TaskHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*asynqpg.TaskInfo))
	})
	return _c
}

func (_c *TaskHandler_Handle_Call) Return(_a0 error) *TaskHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskHandler_Handle_Call) RunAndReturn(run func(context.Context, *asynqpg.TaskInfo) error) *TaskHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskHandler creates a new instance of TaskHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskHandler {
	mock := &TaskHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
