// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/yakser/asynqpg/internal/repository"
)

// CleanerRepo is an autogenerated mock type for the cleanerRepo type
type CleanerRepo struct {
	mock.Mock
}

type CleanerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CleanerRepo) EXPECT() *CleanerRepo_Expecter {
	return &CleanerRepo_Expecter{mock: &_m.Mock}
}

// DeleteOldTasks provides a mock function with given fields: ctx, params
func (_m *CleanerRepo) DeleteOldTasks(ctx context.Context, params repository.DeleteOldTasksParams) (int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldTasks")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteOldTasksParams) (int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteOldTasksParams) int); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteOldTasksParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CleanerRepo_DeleteOldTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldTasks'
type CleanerRepo_DeleteOldTasks_Call struct {
	*mock.Call
}

// DeleteOldTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.DeleteOldTasksParams
func (_e *CleanerRepo_Expecter) DeleteOldTasks(ctx interface{}, params interface{}) *CleanerRepo_DeleteOldTasks_Call {
	return &CleanerRepo_DeleteOldTasks_Call{Call: _e.mock.On("DeleteOldTasks", ctx, params)}
}

func (_c *CleanerRepo_DeleteOldTasks_Call) Run(run func(ctx context.Context, params repository.DeleteOldTasksParams)) *CleanerRepo_DeleteOldTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.DeleteOldTasksParams))
	})
	return _c
}

func (_c *CleanerRepo_DeleteOldTasks_Call) Return(_a0 int, _a1 error) *CleanerRepo_DeleteOldTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CleanerRepo_DeleteOldTasks_Call) RunAndReturn(run func(context.Context, repository.DeleteOldTasksParams) (int, error)) *CleanerRepo_DeleteOldTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewCleanerRepo creates a new instance of CleanerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCleanerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CleanerRepo {
	mock := &CleanerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
