// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/yakser/asynqpg/internal/repository"
)

// RescuerRepo is an autogenerated mock type for the rescuerRepo type
type RescuerRepo struct {
	mock.Mock
}

type RescuerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *RescuerRepo) EXPECT() *RescuerRepo_Expecter {
	return &RescuerRepo_Expecter{mock: &_m.Mock}
}

// FailTasks provides a mock function with given fields: ctx, ids, message
func (_m *RescuerRepo) FailTasks(ctx context.Context, ids []int64, message string) error {
	ret := _m.Called(ctx, ids, message)

	if len(ret) == 0 {
		panic("no return value specified for FailTasks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, string) error); ok {
		r0 = rf(ctx, ids, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RescuerRepo_FailTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailTasks'
type RescuerRepo_FailTasks_Call struct {
	*mock.Call
}

// FailTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
//   - message string
func (_e *RescuerRepo_Expecter) FailTasks(ctx interface{}, ids interface{}, message interface{}) *RescuerRepo_FailTasks_Call {
	return &RescuerRepo_FailTasks_Call{Call: _e.mock.On("FailTasks", ctx, ids, message)}
}

func (_c *RescuerRepo_FailTasks_Call) Run(run func(ctx context.Context, ids []int64, message string)) *RescuerRepo_FailTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64), args[2].(string))
	})
	return _c
}

func (_c *RescuerRepo_FailTasks_Call) Return(_a0 error) *RescuerRepo_FailTasks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RescuerRepo_FailTasks_Call) RunAndReturn(run func(context.Context, []int64, string) error) *RescuerRepo_FailTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetStuckTasks provides a mock function with given fields: ctx, params
func (_m *RescuerRepo) GetStuckTasks(ctx context.Context, params repository.GetStuckTasksParams) ([]repository.StuckTask, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetStuckTasks")
	}

	var r0 []repository.StuckTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetStuckTasksParams) ([]repository.StuckTask, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetStuckTasksParams) []repository.StuckTask); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.StuckTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetStuckTasksParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RescuerRepo_GetStuckTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStuckTasks'
type RescuerRepo_GetStuckTasks_Call struct {
	*mock.Call
}

// GetStuckTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.GetStuckTasksParams
func (_e *RescuerRepo_Expecter) GetStuckTasks(ctx interface{}, params interface{}) *RescuerRepo_GetStuckTasks_Call {
	return &RescuerRepo_GetStuckTasks_Call{Call: _e.mock.On("GetStuckTasks", ctx, params)}
}

func (_c *RescuerRepo_GetStuckTasks_Call) Run(run func(ctx context.Context, params repository.GetStuckTasksParams)) *RescuerRepo_GetStuckTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.GetStuckTasksParams))
	})
	return _c
}

func (_c *RescuerRepo_GetStuckTasks_Call) Return(_a0 []repository.StuckTask, _a1 error) *RescuerRepo_GetStuckTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RescuerRepo_GetStuckTasks_Call) RunAndReturn(run func(context.Context, repository.GetStuckTasksParams) ([]repository.StuckTask, error)) *RescuerRepo_GetStuckTasks_Call {
	_c.Call.Return(run)
	return _c
}

// RetryTask provides a mock function with given fields: ctx, params
func (_m *RescuerRepo) RetryTask(ctx context.Context, params repository.RetryTaskParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RetryTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.RetryTaskParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RescuerRepo_RetryTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryTask'
type RescuerRepo_RetryTask_Call struct {
	*mock.Call
}

// RetryTask is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.RetryTaskParams
func (_e *RescuerRepo_Expecter) RetryTask(ctx interface{}, params interface{}) *RescuerRepo_RetryTask_Call {
	return &RescuerRepo_RetryTask_Call{Call: _e.mock.On("RetryTask", ctx, params)}
}

func (_c *RescuerRepo_RetryTask_Call) Run(run func(ctx context.Context, params repository.RetryTaskParams)) *RescuerRepo_RetryTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.RetryTaskParams))
	})
	return _c
}

func (_c *RescuerRepo_RetryTask_Call) Return(_a0 error) *RescuerRepo_RetryTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RescuerRepo_RetryTask_Call) RunAndReturn(run func(context.Context, repository.RetryTaskParams) error) *RescuerRepo_RetryTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewRescuerRepo creates a new instance of RescuerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRescuerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *RescuerRepo {
	mock := &RescuerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
