// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *Service) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Service_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Service_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Service_Expecter) Name() *Service_Name_Call {
	return &Service_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Service_Name_Call) Run(run func()) *Service_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Name_Call) Return(_a0 string) *Service_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Name_Call) RunAndReturn(run func() string) *Service_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *Service) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Service_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) Start(ctx interface{}) *Service_Start_Call {
	return &Service_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Service_Start_Call) Run(run func(ctx context.Context)) *Service_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_Start_Call) Return(_a0 error) *Service_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Start_Call) RunAndReturn(run func(context.Context) error) *Service_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Service) Stop() {
	_m.Called()
}

// Service_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Service_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Service_Expecter) Stop() *Service_Stop_Call {
	return &Service_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Service_Stop_Call) Run(run func()) *Service_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Stop_Call) Return() *Service_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Service_Stop_Call) RunAndReturn(run func()) *Service_Stop_Call {
	_c.Run(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
