// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	asynqpg "github.com/yakser/asynqpg"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/yakser/asynqpg/internal/repository"
)

// ProducerRepo is an autogenerated mock type for the producerRepo type
type ProducerRepo struct {
	mock.Mock
}

type ProducerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ProducerRepo) EXPECT() *ProducerRepo_Expecter {
	return &ProducerRepo_Expecter{mock: &_m.Mock}
}

// PushTask provides a mock function with given fields: ctx, task
func (_m *ProducerRepo) PushTask(ctx context.Context, task *repository.PushTaskParams) (repository.PushTaskResult, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for PushTask")
	}

	var r0 repository.PushTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.PushTaskParams) (repository.PushTaskResult, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.PushTaskParams) repository.PushTaskResult); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(repository.PushTaskResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.PushTaskParams) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProducerRepo_PushTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushTask'
type ProducerRepo_PushTask_Call struct {
	*mock.Call
}

// PushTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *repository.PushTaskParams
func (_e *ProducerRepo_Expecter) PushTask(ctx interface{}, task interface{}) *ProducerRepo_PushTask_Call {
	return &ProducerRepo_PushTask_Call{Call: _e.mock.On("PushTask", ctx, task)}
}

func (_c *ProducerRepo_PushTask_Call) Run(run func(ctx context.Context, task *repository.PushTaskParams)) *ProducerRepo_PushTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repository.PushTaskParams))
	})
	return _c
}

func (_c *ProducerRepo_PushTask_Call) Return(_a0 repository.PushTaskResult, _a1 error) *ProducerRepo_PushTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProducerRepo_PushTask_Call) RunAndReturn(run func(context.Context, *repository.PushTaskParams) (repository.PushTaskResult, error)) *ProducerRepo_PushTask_Call {
	_c.Call.Return(run)
	return _c
}

// PushTaskWithTx provides a mock function with given fields: ctx, tx, task
func (_m *ProducerRepo) PushTaskWithTx(ctx context.Context, tx asynqpg.Tx, task *repository.PushTaskParams) (repository.PushTaskResult, error) {
	ret := _m.Called(ctx, tx, task)

	if len(ret) == 0 {
		panic("no return value specified for PushTaskWithTx")
	}

	var r0 repository.PushTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, *repository.PushTaskParams) (repository.PushTaskResult, error)); ok {
		return rf(ctx, tx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, *repository.PushTaskParams) repository.PushTaskResult); ok {
		r0 = rf(ctx, tx, task)
	} else {
		r0 = ret.Get(0).(repository.PushTaskResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, asynqpg.Tx, *repository.PushTaskParams) error); ok {
		r1 = rf(ctx, tx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProducerRepo_PushTaskWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushTaskWithTx'
type ProducerRepo_PushTaskWithTx_Call struct {
	*mock.Call
}

// PushTaskWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx asynqpg.Tx
//   - task *repository.PushTaskParams
func (_e *ProducerRepo_Expecter) PushTaskWithTx(ctx interface{}, tx interface{}, task interface{}) *ProducerRepo_PushTaskWithTx_Call {
	return &ProducerRepo_PushTaskWithTx_Call{Call: _e.mock.On("PushTaskWithTx", ctx, tx, task)}
}

func (_c *ProducerRepo_PushTaskWithTx_Call) Run(run func(ctx context.Context, tx asynqpg.Tx, task *repository.PushTaskParams)) *ProducerRepo_PushTaskWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(asynqpg.Tx), args[2].(*repository.PushTaskParams))
	})
	return _c
}

func (_c *ProducerRepo_PushTaskWithTx_Call) Return(_a0 repository.PushTaskResult, _a1 error) *ProducerRepo_PushTaskWithTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProducerRepo_PushTaskWithTx_Call) RunAndReturn(run func(context.Context, asynqpg.Tx, *repository.PushTaskParams) (repository.PushTaskResult, error)) *ProducerRepo_PushTaskWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// PushTasks provides a mock function with given fields: ctx, params
func (_m *ProducerRepo) PushTasks(ctx context.Context, params repository.PushTasksParams) ([]repository.PushTaskResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PushTasks")
	}

	var r0 []repository.PushTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.PushTasksParams) ([]repository.PushTaskResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.PushTasksParams) []repository.PushTaskResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.PushTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.PushTasksParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProducerRepo_PushTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushTasks'
type ProducerRepo_PushTasks_Call struct {
	*mock.Call
}

// PushTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.PushTasksParams
func (_e *ProducerRepo_Expecter) PushTasks(ctx interface{}, params interface{}) *ProducerRepo_PushTasks_Call {
	return &ProducerRepo_PushTasks_Call{Call: _e.mock.On("PushTasks", ctx, params)}
}

func (_c *ProducerRepo_PushTasks_Call) Run(run func(ctx context.Context, params repository.PushTasksParams)) *ProducerRepo_PushTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.PushTasksParams))
	})
	return _c
}

func (_c *ProducerRepo_PushTasks_Call) Return(_a0 []repository.PushTaskResult, _a1 error) *ProducerRepo_PushTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProducerRepo_PushTasks_Call) RunAndReturn(run func(context.Context, repository.PushTasksParams) ([]repository.PushTaskResult, error)) *ProducerRepo_PushTasks_Call {
	_c.Call.Return(run)
	return _c
}

// PushTasksWithTx provides a mock function with given fields: ctx, tx, params
func (_m *ProducerRepo) PushTasksWithTx(ctx context.Context, tx asynqpg.Tx, params repository.PushTasksParams) ([]repository.PushTaskResult, error) {
	ret := _m.Called(ctx, tx, params)

	if len(ret) == 0 {
		panic("no return value specified for PushTasksWithTx")
	}

	var r0 []repository.PushTaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, repository.PushTasksParams) ([]repository.PushTaskResult, error)); ok {
		return rf(ctx, tx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, asynqpg.Tx, repository.PushTasksParams) []repository.PushTaskResult); ok {
		r0 = rf(ctx, tx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.PushTaskResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, asynqpg.Tx, repository.PushTasksParams) error); ok {
		r1 = rf(ctx, tx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProducerRepo_PushTasksWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushTasksWithTx'
type ProducerRepo_PushTasksWithTx_Call struct {
	*mock.Call
}

// PushTasksWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx asynqpg.Tx
//   - params repository.PushTasksParams
func (_e *ProducerRepo_Expecter) PushTasksWithTx(ctx interface{}, tx interface{}, params interface{}) *ProducerRepo_PushTasksWithTx_Call {
	return &ProducerRepo_PushTasksWithTx_Call{Call: _e.mock.On("PushTasksWithTx", ctx, tx, params)}
}

func (_c *ProducerRepo_PushTasksWithTx_Call) Run(run func(ctx context.Context, tx asynqpg.Tx, params repository.PushTasksParams)) *ProducerRepo_PushTasksWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(asynqpg.Tx), args[2].(repository.PushTasksParams))
	})
	return _c
}

func (_c *ProducerRepo_PushTasksWithTx_Call) Return(_a0 []repository.PushTaskResult, _a1 error) *ProducerRepo_PushTasksWithTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProducerRepo_PushTasksWithTx_Call) RunAndReturn(run func(context.Context, asynqpg.Tx, repository.PushTasksParams) ([]repository.PushTaskResult, error)) *ProducerRepo_PushTasksWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducerRepo creates a new instance of ProducerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProducerRepo {
	mock := &ProducerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
